root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/api ./cmd/api/..."
  bin = "./tmp/api"
  args_bin = []
  full_bin = "APP_ENV=local ./tmp/api"
  include_ext = ["go", "yaml"]
  exclude_dir = ["tmp", "vendor", "gen", "migrations"]
  delay = 1000

[log]
  time = false

[misc]
  clean_on_exit = true
